---
data_dir: &data_dir data/cup2_updater_dataset/
vocab:
  vocab_file: !join [*data_dir, mix_vocab.json]
  vocab_embed: !join [*data_dir, mix_vocab_embeddings.pkl]
model:
  model_class: &model_class models.updater.CoAttnBPBAUpdater
  dropout: 0.2
  gen_loss_type: sent_level
train:
  train_data: !join [*data_dir, train.jsonl]
  dev_data: !join [*data_dir, valid.jsonl]
  model_type: &model_type generator
  train_batch_size: 24
  valid_batch_size: 24
  log_every: 100
  valid_niter: 500
  max_epoch: 100
  max_trial_num: 5
  save_to: &save_to model.bin
  seed: 0
infer:
  model_type: *model_type
  beam_size: 5
  batch_size: 64
  max_dec_step: 100
  model_path: *save_to
  test_set_file: &test_set_file !join [*data_dir, test.jsonl]
  output_file: &output_file result.json
  seed: 0
eval:
  eval_class: Evaluator
  test_set: *test_set_file
  result_file: *output_file
