---
data_dir: &data_dir data/cup2_dataset/
vocab:
  vocab_file: !join [*data_dir, mix_vocab.json]
  vocab_embed: !join [*data_dir, mix_vocab_embeddings.pkl]
model:
  model_class: &model_class models.composite.CompositeModel
  com_mode: joint
  clf_loss_func: models.utils.cross_entropy
  gen_loss_type: word_level
train:
  train_data: !join [*data_dir, train.jsonl]
  dev_data: !join [*data_dir, valid.jsonl]
  model_type: &model_type composite
  train_batch_size: &train_batch_size 192
  valid_batch_size: 192
  log_every: 100
  valid_niter: 1300
  max_epoch: 100
  max_trail_num: 5
  dropout: 0
  save_to: &save_to model.bin
  sampler: normal
  pos_train_data: !join [ *data_dir, pos_train.jsonl ]
  neg_train_data: !join [ *data_dir, neg_train.jsonl ]
  seed: 0
infer:
  model_type: *model_type
  batch_size: 384
  beam_size: 5
  max_dec_step: 100
  model_path: *save_to
  test_set_file: &test_set_file !join [*data_dir, test.jsonl]
  output_file: &output_file result
  seed: 0
eval:
  eval_class: CompositeEvaluator
  test_set: *test_set_file
  result_file: *output_file
